---
title: "Gentrification and Displacement in Buffalo, NY"
author: Nino Martinez
subtitle: Using Census and Open Data to Map Neighborhood Change
---

# Introduction
 In recent years, some neighborhoods in Buffalo, NY have experienced a substantial increase in the prosperity of the population, others, however, experienced increasing levels of concentrated disadvantage. Here, I use the definition of gentrification given by The Encyclopedia of Housing as “the process by which central urban neighborhoods that have undergone disinvestments and economic decline experience a reversal, reinvestment, and the in-migration of a relatively well-off, middle- and upper middle class population” (Freeman 2080). Gentrification can displace marginalized populations and most literature document the cause of residential displacement results from increasing rent prices and or home values, no longer affordable for the existing population prior to neighborhood revitalization (LeGates & Hartman 32). Despite the growing demand for up-to-date data that could provide insight into mitigation strategies for the negative consequences of gentrification, only a few studies “attempt to measure gentrification systematically or that document the extent and the form of displacement due to gentrification” (Holm & Schulz, 251).  

> In Rust Belt cities like Buffalo, the [displacement] trend plays out differently than in booming coastal cities like San Francisco and New York. But for all these urban centers, increased public and private investment in downtown neighborhoods combined with changing cultural preferences toward urban lifestyles are changing the fabric of these cities in ways scarcely imagined a decade or two ago.  ~ Danya Sherman

# Materials and methods

1. Open data Buffalo Portal
  - 2018-2019 Assessment Roll (.csv)
  - Neighborhood boundaries (.shp)
2. Census Data
  - 2010 U.S. Census Bureau American Community Survey 5-year Estimates (2006-2010)
  - 2016 U.S. Census Bureau American Community Survey 5-year Estimates (2012-2016)
  - City census tract/block groups (not sure yet) boundaries (.shp)
  
<br>While traditional methods of measuring gentrification rely heavily upon the use of analyzing key indicators of gentrification, such as increasing percentage of white population, higher incomes, and rents (Heidkamp & Lucas, 104). This methodology is not able to analyze changing neighborhood dynamics in close-to-real time due to the infrequency of community surveys and the year lag time of results. In addition, as the geographic unit gets smaller, accuracy of the data also diminishes due to higher margins of error, thus blurring both perceived and established neighborhood boundaries as well as the dynamics of change. New methods of quantifying changing cities arose from the “emerging cloud of Big Data”, and prove useful to supplement traditional methods of measuring gentrification and displacement (Zook et al., 2). Open data portals provided by local government agencies are also incredibly valuable. These publically available datasets can provide useful information on neighborhood change at the individual level.</br>

<br>In recent years, some residential tax parcels have sold for much more than the assessed value and are located in neighborhoods where revitalization efforts have taken place. The total assessment value of each residential tax parcel determines how much a homeowner pays in property taxes each year, thus contributes to the development of city infrastructure. The purpose of this project is to use the city of Buffalo’s Open Data Portal to analyze and visualize gentrification based on the sold price of residential tax parcels above the total assessment value and understand which changing socioeconomic variables play the largest role the amount sold price was over the assessment value.  By using R Studio, I will filter the dataset to only include residential tax parcels that were sold between 2010 and 2016 for higher than the assessed value, which I will then group by census tract to portray descriptive statistics for each neighborhood. By using census data provided by the U.S. Census Bureau’s American Community Survey 5-year estimates for 2010 and 2016, I will analyze the socioeconomic change of key indicators of gentrification documented in the literature, also at the census tract level. In order to model this relationship, I will use a multivariate regression model to test the strength of the relationships.</br>

See [http://rmarkdown.rstudio.com/](http://rmarkdown.rstudio.com/) for all the amazing things you can do.


Here's my first code chunk.

Load any required packages in a code chunk (you may need to install some packages):


# Results

Show tables, plots, etc. and describe them.



# Conclusions

What have you learned?  Are there any broader implications?

# References 

Freeman, Lance (2009). Neighbourhood Diversity, Metropolitan Segregation and Gentrification: What Are the Links in the US? Urban Studies 46(10), 2079-2101.

Holm, Andrej & Schulz, Guido (2017). Gentrimap: A Model for Measuring Gentrification and Displacement. Gentrification and Resistance: Researching Displacement Processes and Adaption Strategies. Springer VS, 251-277

Heidkamp, Patrick C & Lucas, Susan (2006). Finding the Gentrification Frontier Using Census Data: The Case of Portland, Maine. Urban Geography 27(2), 101-125.

LeGates, R., & Hartman, C. (1982). Gentrification-Caused Displacement. The Urban Lawyer, 14(1), 31-55. 

Zook et al (2017). Big Data and the City. Handbook of Urban Geography, 1-12.

